version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: laravel-horizon-app
    container_name: laravel-horizon-app
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
    environment:
      - APACHE_RUN_USER=www-data
      - APACHE_RUN_GROUP=www-data
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: laravel-horizon-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: laravel
      MYSQL_USER: laraveluser
      MYSQL_PASSWORD: laravelpassword
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql

  horizon:
    build:
      context: .
      dockerfile: Dockerfile
    image: laravel-horizon-app
    container_name: laravel-horizon-worker
    volumes:
      - ./:/var/www/html
    depends_on:
      - app
    command: php artisan horizon

volumes:
  dbdata:
